### ISSUE TITLE
Won't work with BibDesk v1.7.5 

### ISSUE THREAD

**Issue by r-xue** [r-xue/ads2bibdesk#11]
One will get an error message from the AppleScript call of adding new BibTeX entries.
```
BibDesk got an error: document 1 doesn’t understand the “import” message.
```
temporary workaround: just don't upgrade to BibDesk v1.7.5 util the change is clarified.
 
**update**: reported the [bug](https://sourceforge.net/p/bibdesk/bugs/1568) to the BibDesk developers and it will be fixed in their next release.

**Comment by bwholwerda** [comment]
Not sure if this is the same bug but with ads2bibdesk I now get the following issue:

"
    article_status=process_token(args.article_identifier, prefs, bibdesk)
  File "/Users/holwerda/Programs/ads2bibdesk-master/ads2bibdesk.py", line 234, in process_token
    pub = pub.descriptorAtIndex_(1).descriptorAtIndex_(3).stringValue()
AttributeError: 'NoneType' object has no attribute 'descriptorAtIndex_'
"

Is this a bib desk issue or a ads2bibdesk issue?

**Comment by keflavich** [comment]
I think it's an interaction between the two; older bibdesk will still work.

**Comment by r-xue** [comment]
_some background info:_

**ads2bibdesk** communicates with [BibDesk via AppleScript](https://bibdesk.sourceforge.io/manual/BibDeskHelp_79.html#SEC142) (also see [here](https://sourceforge.net/p/bibdesk/wiki/BibDesk_Applescripts/?version=3)). It doesn't manipulate the BibTeX file directly. 

However, some scripting functions offered by **BibDesk** are broken in its latest v1.7.5 release (see the attachment for an example test, specifically related to the ```import from "@article..."``` call).
Just as @keflavich mentioned, this causes a communication issue. 

I can't do much about it. But the **BibDesk** people have fixed it in their nightly build and will include the change in their next release (hopefully).

[as_test_importfrom.scpt.zip](https://github.com/r-xue/ads2bibdesk/files/4439467/as_test_importfrom.scpt.zip)

**Comment by keflavich** [comment]
Thanks for the additional info @r-xue.  I actually found this issue by googling for the error string as I was trying to debug this issue too.  I'm glad you've already identified and kinda solved it.

**Comment by r-xue** [comment]
No problem!

**Comment by jmccormac01** [comment]
I'm having the same issue as @bwholwerda. Which version of bibdesk do you suggest I roll back to? Thanks.

**Comment by r-xue** [comment]
1.7.4 should be fine.

**Comment by r-xue** [comment]
BibDesk 1.7.6 is out and has fixed the bug.
